version: '3.7'

services:
  api:
    image: tijmenwierenga/demo-api:latest
    build: .
    ports:
    - 80:80
    volumes:
    - .:/app
    working_dir: /app
    command: >
      /bin/ash -c "composer install &&
                   php -S 0.0.0.0:80 -t public"

  database:
    image: mysql:8
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=secret-password
    - MYSQL_DATABASE=demo
    volumes:
    - ./database/:/docker-entrypoint-initdb.d/

  mock:
    image: stoplight/prism:latest
    ports:
    - 3100:3100
    volumes:
    - ./reference:/reference
    command: mock -h 0.0.0.0 -p 3100 /reference/demo-api.v1.yaml

  docs:
    image: redocly/redoc:latest
    ports:
    - 8080:80
    volumes:
    - ./reference/:/usr/share/nginx/html/spec/
    environment:
    - SPEC_URL=spec/demo-api.v1.yaml
